name: Maven Build and Run Selenium Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      # Step 3: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Install Chrome and ChromeDriver
      - name: Set up Chrome and ChromeDriver
        run: |
          # Install Google Chrome using Chocolatey
          choco install googlechrome --no-progress --yes

          # Get Chrome version from the binary
          $chromePath = \"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\"
          if (-Not (Test-Path $chromePath)) {
              $chromePath = \"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"
          }
          $chromeVersion = (Get-Command $chromePath).FileVersionInfo.ProductVersion
          echo \"Installed Chrome version: $chromeVersion\"

          # Get ChromeDriver version compatible with Chrome
          $chromeMajorVersion = $chromeVersion.Split('.')[0]
          $chromeDriverVersion = Invoke-RestMethod -Uri \"https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chromeMajorVersion\"
          echo \"Installing ChromeDriver version: $chromeDriverVersion\"

          # Download and install ChromeDriver
          Invoke-WebRequest -Uri \"https://chromedriver.storage.googleapis.com/$chromeDriverVersion/chromedriver_win32.zip\" -OutFile chromedriver_win32.zip
          Expand-Archive -Path chromedriver_win32.zip -DestinationPath . -Force
          Move-Item -Path .\\chromedriver.exe -Destination C:\\Windows\\System32\\chromedriver.exe -Force

      # Step 5: Verify Chrome and ChromeDriver Versions
      - name: Verify Chrome and ChromeDriver
        run: |
          \"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\" --version
          chromedriver --version

      # Step 6: Run tests with Maven
      - name: Run Maven Tests
        run: mvn clean test -B --file pom.xml
